[platformio]
src_dir = inky_ESP32_13inch

[env:esp32-s3-first-light]
platform = espressif32
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = partitions_16mb_cache.csv
build_src_filter =
    +<*>
    -<removed/>
    -<archive/>
lib_deps =
    https://github.com/vshymanskyy/TinyGSM.git
    arduino-libraries/ArduinoHttpClient@^0.6.1
    digitaldragon/SSLClient@^1.3.1
    bblanchon/ArduinoJson@^7.2.1
    bitbank2/JPEGDEC@^1.8.2
    bitbank2/PNGdec@^1.1.2
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -D TINY_GSM_MODEM_SIM7600
    -D TINY_GSM_RX=11
    -D TINY_GSM_TX=10
    -D NFC_SDA=1
    -D NFC_SCL=2
    -D NFC_INT=21
    -D POWER_ENABLE_GPIO=4
    -D IDLE_SLEEP_MS=300000
    -DBOARD_HAS_PSRAM
